eureka:
  client:
    serviceUrl:
      defaultZone: http://freeChildren:eureka666666@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
